<h1>After <a href="http://travis-ci.org/Raynos/after"><img src="https://secure.travis-ci.org/Raynos/after.png" alt="Build Status"></a></h1><p>Invoke callback after n calls</p>
<h2>Status: production ready</h2><h2>Example</h2><pre><code class="language-js">var after = require(&quot;after&quot;)
var db = require(&quot;./db&quot;) // some db.

var updateUser = function (req, res) {
  // use after to run two tasks in parallel,
  // namely get request body and get session
  // then run updateUser with the results
  var next = after(2, updateUser)
  var results = {}

  getJSONBody(req, res, function (err, body) {
    if (err) return next(err)

    results.body = body
    next(null, results)
  })

  getSessionUser(req, res, function (err, user) {
    if (err) return next(err)

    results.user = user
    next(null, results)
  })

  // now do the thing!
  function updateUser(err, result) {
    if (err) {
      res.statusCode = 500
      return res.end(&quot;Unexpected Error&quot;)
    }

    if (!result.user || result.user.role !== &quot;admin&quot;) {
      res.statusCode = 403
      return res.end(&quot;Permission Denied&quot;)
    }

    db.put(&quot;users:&quot; + req.params.userId, result.body, function (err) {
      if (err) {
        res.statusCode = 500
        return res.end(&quot;Unexpected Error&quot;)
      }

      res.statusCode = 200
      res.end(&quot;Ok&quot;)  
    })   
  }
}
</code></pre>
<h2>Naive Example</h2><pre><code class="language-js">var after = require(&quot;after&quot;)
    , next = after(3, logItWorks)

next()
next()
next() // it works

function logItWorks() {
    console.log(&quot;it works!&quot;)
}
</code></pre>
<h2>Example with error handling</h2><pre><code class="language-js">var after = require(&quot;after&quot;)
    , next = after(3, logError)

next()
next(new Error(&quot;oops&quot;)) // logs oops
next() // does nothing

// This callback is only called once.
// If there is an error the callback gets called immediately
// this avoids the situation where errors get lost.
function logError(err) {
    console.log(err)
}
</code></pre>
<h2>Installation</h2><p><code>npm install after</code></p>
<h2>Tests</h2><p><code>npm test</code></p>
<h2>Contributors</h2><ul>
<li>Raynos</li>
<li>defunctzombie</li>
</ul>
<h2>MIT Licenced</h2>